--CRIAÇÃO DO BANCO DE DADOS
--CREATE DATABASE SP_MEDICAL_GROUP

--DEFININDO USUARIO PARA "SP_MEDICAL_GROUP"
--USE SP_MEDICAL_GROUP

CREATE TABLE TIPO_USUARIOS(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(250) UNIQUE NOT NULL  
);

CREATE TABLE AREAS_ATUACOES(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(250) UNIQUE NOT NULL
);

CREATE TABLE CLINICAS(
	ID INT IDENTITY(1,1) PRIMARY KEY
	,NOME VARCHAR(250) NOT NULL
	,ENDERECO VARCHAR(250) NOT NULL
	,CNPJ CHAR(14) UNIQUE NOT NULL
	,CEP CHAR(8) NOT NULL
	,RAZAO_SOCIAL VARCHAR(250) NOT NULL
);

CREATE TABLE USUARIOS(
	ID INT IDENTITY(1,1) PRIMARY KEY
	,EMAIL VARCHAR(250) NOT NULL
	,SENHA VARCHAR(250) NOT NULL
	,ID_TIPO_USUARIO INT NOT NULL FOREIGN KEY REFERENCES TIPO_USUARIOS(ID)
	);

CREATE TABLE PRONTUARIOS(
	ID INT IDENTITY(1,1) PRIMARY KEY
	,ID_USUARIO INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(ID)
	,RG CHAR(10) NOT NULL UNIQUE 
	,CPF CHAR(11) NOT NULL UNIQUE
	,TELEFONE CHAR(11)
	,ENDERECO VARCHAR(250) NOT NULL
	,DATA_NASCIMENTO DATE NOT NULL
);

CREATE TABLE MEDICOS(
	ID INT IDENTITY(1,1) PRIMARY KEY
	,NOME VARCHAR(250) NOT NULL
	,CRM VARCHAR(13) NOT NULL
	,ID_USUARIO INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(ID)
	,ID_AREA_ATUACAO INT NOT NULL FOREIGN KEY REFERENCES AREAS_ATUACOES(ID)
	,ID_CLINICA INT NOT NULL FOREIGN KEY REFERENCES CLINICAS(ID)
);

CREATE TABLE CONSULTAS(
	ID INT IDENTITY(1,1) PRIMARY KEY
	,ID_PRONTUARIO INT NOT NULL FOREIGN KEY REFERENCES PRONTUARIOS(ID)
	,ID_MEDICO INT NOT NULL FOREIGN KEY REFERENCES MEDICOS(ID)
	,DATA_HORA DATETIME NOT NULL
	,DESCRICAO TEXT NOT NULL
	,STATUS VARCHAR(250) NOT NULL
);


--CRIAÇÃO DE UMA PROCEDURE PARA VALIDAÇÃO DE EMAIL E SENHA
GO
CREATE PROCEDURE USUARIO_VALIDACAO
	@EMAIL VARCHAR(250) 
	,@SENHA VARCHAR(250)
	,@ID_TIPO_USUARIO INT
	AS
	BEGIN
	IF  (@EMAIL LIKE '%_@%'
	   AND @EMAIL LIKE '%.%'
	   AND @EMAIL NOT LIKE '%._@%'
	   AND @EMAIL NOT LIKE '%@.%'
	   AND LEN(@SENHA) >= 6
	   AND @SENHA IS NOT NULL)

INSERT USUARIOS
(EMAIL,SENHA,ID_TIPO_USUARIO) VALUES (@EMAIL,@SENHA,@ID_TIPO_USUARIO)

	ELSE
	PRINT ('Email OU Senha inválidos')
	END

--CRIAÇÃO DE PROCEDURE PARA VALIDACAO DE CPF
GO
CREATE PROCEDURE CPF_VALIDACAO
	@CPF CHAR(11)
	AS
	BEGIN
	IF (LEN(@CPF) = 11
	AND NOT LEN(@CPF) > 11  
	AND @CPF IS NOT NULL
	AND @CPF != ''
 	AND @CPF NOT LIKE '%-%'
	AND @CPF NOT LIKE '%*%'
	AND @CPF NOT LIKE '%#%'
	AND @CPF NOT LIKE '%@%'
	AND @CPF NOT LIKE '%!%')

	INSERT PRONTUARIOS
	(CPF) VALUES (@CPF)

	ELSE
	PRINT ('CPF Invalido')
	END



------------------------------------------------------
/*DROP PROCEDURE EMAIL_VALIDACAO

DROP TABLE USUARIOS

DROP TABLE TIPO_USUARIO

DROP TABLE CLINICAS

DROP TABLE MEDICOS

DROP TABLE CONSULTAS

alter table CONSULTAS ALTER COLUMN DESCRICAO TEXT NULL

SELECT * FROM USUARIOS

SELECT * FROM TIPO_USUARIOS

DROP PROCEDURE CPF_VALIDACAO*/